<?
$PERM["managed_cache"]["2"]="X";
$PERM["managed_cache"]["5"]="X";
$PERM["managed_cache"]["3"]="X";
$PERM["managed_cache"]["4"]="X";
$PERM["managed_cache"]["9"]="X";
$PERM["managed_cache"]["8"]="X";
$PERM["managed_cache"]["6"]="X";
$PERM["managed_cache"]["7"]="X";
$PERM["managed_cache"]["*"]="X";
$PERM["cache"]["2"]="X";
$PERM["cache"]["5"]="X";
$PERM["cache"]["3"]="X";
$PERM["cache"]["4"]="X";
$PERM["cache"]["9"]="X";
$PERM["cache"]["8"]="X";
$PERM["cache"]["6"]="X";
$PERM["cache"]["7"]="X";
$PERM["cache"]["*"]="X";
$PERM["admin"]["8"]="R";
$PERM["admin"]["6"]="R";
$PERM["admin"]["7"]="R";
$PERM["admin"]["*"]="D";
$PERM["admin"]["9"]="R";
?>